### ISSUE TITLE
ip parameter

### ISSUE THREAD

**Issue by vicMolina** [jhthorsen/docsis-configfile#11]
When I try to encode my file with this parameter SwUpgradeServer => 192.168.60.10, the program send me this error ip({ value => ÃÂ¨=Ã¼ }) does not match (?^:^(?:\d{1,3}\.){3}\d{1,3}$) at /usr/local/share/perl/5.22.1/DOCSIS/ConfigFile/Encode.pm line 484.

If I use TftpModemAddress  => 192.168.60.10, I get the same error.

I'm using the follow guide: https://metacpan.org/pod/DOCSIS::ConfigFile::Syminfo#CONFIGURATION-TREE

thank you

Regards

**Comment by jhthorsen** [comment]
Just to be sure, do you quote that address..? I think it should work:

https://github.com/jhthorsen/docsis-configfile/blob/266196188ad7ceab756104c05455ef1bece704e5/t/complex.t#L175

**Comment by vicMolina** [comment]
Thank's very much
