### ISSUE TITLE
Docsisious icons?

### ISSUE THREAD

**Issue by neo-neo1** [jhthorsen/docsis-configfile#16]
On the main [README](https://github.com/jhthorsen/docsis-configfile/blob/master/README.md), all the links for Docsisious icons are dead.

**Comment by jhthorsen** [comment]
I’m guessing “discussion” is “Docsisious”.

I wonder how to fix that. Maybe I should replace the icons completely...

**Comment by neo-neo1** [comment]
Yes, sorry about the typo.

**Comment by neo-neo1** [comment]
> I’m guessing “discussion” is “Docsisious”.
> 
> I wonder how to fix that. Maybe I should replace the icons completely...

Yes, sorry about the typo.
