### ISSUE TITLE
Support for Gauge32 OID value type

### ISSUE THREAD

**Issue by aholtzmbw** [jhthorsen/docsis-configfile#17]
Curious if it would be possible to add Gauge32 as an OID value type?  Just to clarify I'd like it added to the existing options like String, Integer, etc.  I've run into some MTAs that want to set the SIP port using Gauge32 instead of something like Integer.

Thanks.

**Comment by jhthorsen** [comment]
I don’t think that should be too difficult. I think we just have to add a new line to https://github.com/jhthorsen/docsis-configfile/blob/7a8ce3307c7bcc5c44329e888ac2a5cadd548437/lib/DOCSIS/ConfigFile/Encode.pm#L9

I wonder if there’s other types that I forgot to add...

**Comment by aholtzmbw** [comment]
I was thinking the same thing and was going to try it out - my thought was to just point it to \&uint like some of the other 32-bit counters.  This is the first time I've run into this type.  Here is a table from Cisco that talks about the types and the values they should contain (they show GAUGE32 as a type "GAUGE" and not "INTEGER" so not sure if that's something different).

https://www.cisco.com/c/en/us/td/docs/net_mgmt/broadband_access_center_for_cable/4-1/administration/guide/AdminGuide4-1/Configuration_Templates_Management.html#wp1215825

**Comment by jhthorsen** [comment]
I'm going to close this, since there haven't been any work done for a long time.
