### ISSUE TITLE
Unknown SNMP type: HEXSTR

### ISSUE THREAD

**Issue by vega480** [jhthorsen/docsis-configfile#18]
When trying to download a binary config I am getting an error through the online docsisious.
Cannot encode config file: Unknown SNMP type: HexString
These are valid config files in use. When I decode one that has has a HexString value in them it seems to change it to a String. In the parameters list it does show a few using hexstr. I have tried changing the type to HexStr and still errors. In the code it seems to support it, but not showing in the our %SNMP_TYPE, if I am reading it right it should be in there.

What I am entering in the textarea:
```
---
SnmpMibObject:
- HexString: 0x80
  oid: 1.3.6.1.4.1.4413.2.2.2.1.2.2.1.1.5.10
```

**Comment by jhthorsen** [comment]
Sorry for the very late reply. I think the problem is that you need "HEXSTRING" and not "HexString".
