### ISSUE TITLE
'encode_docsis' generates truncated config

### ISSUE THREAD

**Issue by dmalopsy** [jhthorsen/docsis-configfile#7]
Passing a long list to key SingleDsChannel causes 'encode_docsis' to generate a truncated config and throws error:
`Character in 'C' format wrapped in pack at /usr/local/share/perl/5.20.2/DOCSIS/ConfigFile.pm line 268`

Attached below is an example data structure that can be used with 'encode_docsis' to trigger the error:
[longdschannellist.txt](https://github.com/jhthorsen/docsis-configfile/files/762814/longdschannellist.txt)

At 21'SingleDsChannel' entries or less it is fine, however 22 or more entries triggers the bug.

I am using an old version of this module, however I have been able to replicate the problem on version 0.71.

**Comment by jhthorsen** [comment]
I have not looked into this yet, but can you show me in the specification where you can specify more than 21 entries? Could there be a limitation in the spec?

**Comment by dmalopsy** [comment]
`267       $type = pack 'C', $syminfo->{code};
268       $length = $syminfo->{lsize} == 2 ? pack('n', length $value) : pack('C', length $value);
269       $mic->{$name} = "$type$length$value";
270       $bytes .= $mic->{$name};
271     }`

The dschannellists $value's length is > 255, so the pack of a single C causes it to wrap - hence the error.

I am not sure if its legal to have the length of value of the channels longer than 255? it may be implicitly illegal if the $length position is limited to 8 bits? i poked around in the spec's but honestly, got lost trying to get a clear answer.

**Comment by jhthorsen** [comment]
It would be interesting to see how another encoder solves this. If you can create a config file with the desired result and then attach the binary file, I can try to parse that file and fix this module.

Reason for me being rather passive on this, is because I have not been into DOCSIS tech for over ten years.

**Comment by dmalopsy** [comment]
No problem I was pleasantly surprised how quick you responded.

I found that DOCSIS Configuration File creator (which is now here https://github.com/rlaager/docsis) does compile the config however with a "warning: aggregate size of settings block larger than 255, skipping". Decoding it back confirms that it did not include the DsChannelList. So it is more likely that this is not a bug. For now I am treating it as a non issue and exploring alternatives like spiting up the list into two.

Apologies for wasting your time.

**Comment by djzort** [comment]
it may be better to check that length <256 and throw a meaningful error?

**Comment by jhthorsen** [comment]
I'm re-opening this because I think that DOCSIS::ConfigFile should croak/die on invalid input.

**Comment by jhthorsen** [comment]
Sorry for the long wait. This is now fixed.
